language: rust
sudo: required
script:
- "./framework-setup.sh"
- cargo build --verbose --release
env:
- VERBOSE=1
os:
- osx
- linux
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: QnaLaRT5Q6RgFe65GoqjEwQlYG7FUdAApw1+uDcAZ7pA5cv4gipHH27iCqdmVPiKNZnpab6+NlLcgtvcZK2Z4rYVUEPT0BIikoN07XmiO8SIdYVEZNs4whL23qMQMeLtCQPx5LmTHWUNeDUbUgdnQA9q1uFvJS719Q50efPjy17kOvKben9bsfU2sGLAQJPyDkZiZEjOcksiUGy+W3mynKF4y9h+uHNeDxHZKFQsJDODZfjjxNsQwnO0ValL4vhpWlG2SB6V0XOFAbnNfmwzmmhzbnvtl/E50uGVOg2iOLqjbwy6hakPpH1PHvKxBqhbg2q2qBfNPuEc0m72Q7wdEBAR258rAsmyhoRqoUqExYTHlQ4p8atfDGrUD9BfA9mKgs3omLCgKYBt7P8MZhDsnmQUHefL6SsaKD8C4L0BJR6XgUMX1nTDl/kZxYusRw7TnFPbNRCzXSVAWvcBW/NlWw1AutIXuC3B4JG/u4kRxknynIhaRIfQuXHHp/NyIiFWGeddsJLV4eygd1k5ptGzF3rDjiNP7YpMIToDznB1cc1U8mz7y2kKXdVcQ/cWIlKrSVhNu8XwF6x0oh92PjIa+u8yjAfbRmeelICvHKy0NAkLJ+i7I/fSlMOc7a+83/EKx7AdyrTI8vLhagaRwwf06WHrK5iDWi0E6sT3obNUTEE=
  file: "./target/release/dotfiles"
  on:
    repo: PsychoLlama/dotfiles
    # Only compile on experimental Rust branch.
    # TODO: Change this to `master` once merged.
    branch: what-if-rust
