[package]
name = "dotfiles"
version = "0.1.0"
authors = ["Jesse Gibson <Jesse_Gibson@me.com>"]

[dependencies]
serde_json = "1.0.9"
ansi_term = "0.10.2"

[dependencies.clap]
version = "~2.29.2"
features = ["suggestions", "color", "wrap_help"]
