#!/usr/bin/env zsh
# Creates a manifest dictionary drawing from
# defaults, merged with the environment preset.

# Bash 4 is required for hash tables, but mac is stuck on bash 3.
# Zsh to the rescue.
typeset -A MANIFEST
MANIFEST[vim-info]=~/.viminfo
MANIFEST[vim-backup]=~/.vim/backup/
MANIFEST[vim-undo-history]=~/.vim/undodir/
MANIFEST[repl-history-node]=~/.node_repl_history
MANIFEST[repl-history-python]=~/.python_history
MANIFEST[zsh-history]=~/.zsh_history
MANIFEST[zoxide-weights]=~/.zo

env_manifest=~/dotfiles-env/eject-manifest.sh
if [[ -f "$env_manifest" ]]; then
  source "$env_manifest"

  # Merge the env & base manifests.
  for env_dest in "${(k)DOTFILES_MANIFEST[@]}"; do
    MANIFEST[$env_dest]="${DOTFILES_MANIFEST[$env_dest]}"
  done
fi


export MANIFEST
