#!/usr/bin/env bash
set -e

# Supported environments:
# - Ubuntu Xenial (docker compatible)
# - OS X High Sierra

function cmd_exists {
  command -v "$1" &> /dev/null
}

function as_root {
  # This could be run in a docker container.
  if [[ "$(whoami)" == "root" ]]; then
    "$@"
  elif cmd_exists sudo; then
    command sudo "$@"
  else
    echo "Root privileges required for command '$*'."
    echo "Install sudo then try again."
    exit 1
  fi
}

if cmd_exists apt-get; then
  as_root apt-get update
fi

# Resolve the absolute path of the current file.
pushd "$(dirname "$0")" &> /dev/null
DOTFILES_DIR="$(pwd -P)"
popd &> /dev/null

# Make the `dotfiles` command.
as_root ln -sf "$DOTFILES_DIR/dotfiles" "/usr/local/bin/dotfiles"

# Some installs (like neovim) depend on these symlinks.
dotfiles link > /dev/null

# oh-my-zsh freaks if it sees another .zshrc file.
rm ~/.zshrc
dotfiles install
dotfiles link

if [[ "$SHELL" != "$(which zsh)" && -z "$CI" ]]; then
  exec zsh
fi
