[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]

[formatter.just]
command = "just"
options = ["--fmt", "--justfile"]
includes = ["justfile", "**/justfile", "*.just"]
no-positional-arg-support = true
