set default-list := true

# Update the chrome-devtools-mcp package.
update-chrome-devtools-mcp:
  ./chrome-devtools-mcp/update.sh

# Update the codex package.
update-codex:
  ./codex/update.sh

# Update the claude-code package.
update-claude-code:
  ./claude-code/update.sh

# Update the nvim-rs package.
update-nvim:
  ./nvim-rs/update.sh

# Update all custom packages.
update: update-chrome-devtools-mcp update-codex update-claude-code update-nvim
