[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
