#!/usr/bin/env bash
set -e

# No args.
if [[ "$#" == 0 ]]; then
  echo "Usage: viml <scriptfile>"
  exit 1
fi

# Invalid file.
if [[ ! -f "$1" ]]; then
  echo "Error: no such file '$1'" >&2
  exit 1
fi

arg_file=/tmp/viml_argv_
arg_index=0
for arg in "$@"; do
  echo "$arg" > "${arg_file}${arg_index}"
  arg_index="$((arg_index + 1))"
done

setup="source $(dotfiles dir)/utils/headless-env.vim"
VIML_ARGV_FILE="$arg_file" VIML_ARGV_COUNT="$arg_index" \
  nvim --headless -u NONE -c "$setup" 2>&1
