#!/usr/bin/env bash
set -e

# No args.
if [[ "$#" == 0 ]]; then
  echo "Usage: viml <scriptfile>"
  exit 1
fi

# Invalid file.
if [[ ! -f "$1" ]]; then
  echo "Error: no such file '$1'" >&2
  exit 1
fi

setup="
let g:__sourcefile = '$1'
source $(dotfiles dir)/utils/headless-env.vim
"

nvim --headless -u NONE -c "$setup"
