[formatter.stylua]
command = "stylua"
includes = ["*.lua"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]

[formatter.just]
command = "just"
options = ["--fmt", "--justfile"]
includes = ["justfile"]
no-positional-arg-support = true
