add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$git_state \
$character
"""

[directory]
format = "[$path](blue)"
truncation_length = 1

[git_branch]
format = "[\\[](yellow)[$branch](cyan)[\\]](yellow)"
