{
  # Partially generated by `nixos-generate-config`.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];

  boot.kernelModules = [
    "kvm-intel"

    # Bluetooth HID Profile. Without this, BT keyboards/mice connect at the
    # L2CAP layer but never attach to the kernel input subsystem (no key
    # events). BlueZ does not autoload it on this system.
    "hidp"
  ];

  # Disable nouveau runtime power management. Without this, the NVIDIA GPU
  # enters a deep sleep state that corrupts HDMI connector detection after
  # suspend/hibernate. Trade-off: slightly higher power draw when mobile.
  boot.kernelParams = [ "nouveau.runpm=0" ];
  hardware.bluetooth.enable = true;

  fileSystems =
    let
      zfs = path: {
        device = "locker/${path}";
        fsType = "zfs";
        options = [ "zfsutil" ];
      };
    in

    {
      # Only the ZFS pool and boot partition are persisted. Everything else is
      # volatile.
      "/" = {
        device = "none";
        fsType = "tmpfs";
        options = [ "mode=755" ];
      };

      "/boot" = {
        device = "/dev/disk/by-label/boot";
        fsType = "vfat";
      };

      "/nix" = zfs "nixos/nix";
      "/etc" = zfs "nixos/etc";
      "/var" = zfs "nixos/var";
      "/var/lib" = zfs "nixos/var/lib";
      "/var/log" = zfs "nixos/var/log";
      "/var/spool" = zfs "nixos/var/spool";
      "/home" = zfs "data/home";
      "/root" = zfs "data/home/root";
      "/home/overlord" = zfs "data/home/overlord";
    };

  swapDevices = [
    {
      # This is a stable identifier for `/dev/disk/by-label/swap`.
      device = "/dev/disk/by-partuuid/dc08f0f5-451d-483d-af2a-efca672f4897";

      # Note: Encryption can potentially corrupt hibernation state. This isn't
      # a problem as hibernation is currently disabled for ZFS support.
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = "x86_64-linux";
}
