{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./bottom.nix
    ./direnv.nix
    ./dive.nix
    ./doggo.nix
    ./eza.nix
    ./fd.nix
    ./firefox.nix
    ./fzf.nix
    ./git.nix
    ./glow.nix
    ./jq.nix
    ./miniserve.nix
    ./ncspot.nix
    ./neovim.nix
    ./nmap.nix
    ./nushell.nix
    ./rofi.nix
    ./sshfs.nix
    ./starship.nix
    ./swaylock.nix
    ./termshark.nix
    ./tmux.nix
    ./viddy.nix
    ./waybar.nix
    ./wezterm.nix
    ./whois.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
