{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./bottom.nix
    ./direnv.nix
    ./dive.nix
    ./dogdns.nix
    ./eza.nix
    ./fd.nix
    ./fzf.nix
    ./git.nix
    ./glow.nix
    ./jq.nix
    ./miniserve.nix
    ./ncspot.nix
    ./neovim.nix
    ./nmap.nix
    ./nushell.nix
    ./sshfs.nix
    ./starship.nix
    ./termshark.nix
    ./tmux.nix
    ./w3m.nix
    ./whois.nix
    ./xh.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
