#!/usr/bin/env bash
set -e

# Symlink stuff from the config/ directory
# Constraints:
# - Bash v3 compatible (no hashmaps)
# - No ./install specific tooling (this runs before ./install)

dotfiles_dir="$(dotfiles dir)"
yellow='\033[0;33m'
green='\033[0;32m'
gray='\033[1;37m'
red='\033[0;31m'
reset='\033[0;0m'

function show_error {
  echo -e "${red}Error:$reset" "$*" 1>&2
}

function shorten_path {
  sed "s+$HOME+~+" <<< "$1"
}

function resolve_path {
  local dest="$1"

  if [[ "${dest:0:1}" == '/' ]]; then
    echo "$1"
  else
    echo "$dotfiles_dir/config/$1"
  fi
}

function validate_targets {
  while read -r src dest; do
    local dest_path="$(resolve_path "$dest")"

    if [[ ! -f "$dest_path" ]]; then
      show_error Skipping nonexistent file \
        "$gray($dest_path)$reset"
    fi

    echo "$src" "$dest"
  done
}

function create_link {
  local target_folder="$(dirname "$1")"
  local src="$(shorten_path "$1")"
  local dest="$(resolve_path "$2")"
  local pretty_dest="$(shorten_path "$dest")"

  mkdir -p "$target_folder"

  ln -sf "$dest" "$1" || {
    local plan="$gray($reset$src $green=>$reset $pretty_dest$gray)$reset."
    show_error "Symlink failed $plan"
    return 1
  }

  echo -e "$yellow{$reset $src $green=>$reset $pretty_dest $yellow}$reset"
}

function process_manifest_output {
  while read -r src dest; do
    create_link "$src" "$dest"
  done
}

# shellcheck source=config/manifest.sh
source "$dotfiles_dir/config/manifest.sh"

get_dotfiles_manifest \
  | validate_targets \
  | process_manifest_output
