name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludvighz/vint-action@v1
        with:
          path: ./
          args: '--color'
